# Generated by Django 4.2 on 2024-08-21 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('date', models.DateTimeField()),
                ('method', models.CharField(max_length=10)),
                ('uri', models.CharField(max_length=255)),
                ('resp_code', models.PositiveIntegerField()),
                ('resp_bytes', models.PositiveBigIntegerField()),
            ],
        ),
    ]
