# Generated by Django 4.2 on 2024-08-22 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_fix', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logs',
            name='date',
            field=models.DateTimeField(null=True),
        ),
    ]
