# Generated by Django 4.2 on 2024-08-22 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_fix', '0002_alter_logs_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logs',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
